apiVersion: batch/v1
kind: Job
metadata:
  name: multiple-batch-job
spec:
  completions: 20
  parallelism: 20
  activeDeadlineSeconds: 5
  backoffLimit: 0
  template:
    metadata:
      labels:
        name: multiple-batch-job
    spec:
      restartPolicy: Never
      containers:
      - name: multiple-batch-job
        image: luksa/batch-job