apiVersion: v1
kind: ReplicationController
metadata:
  name: nodejs-app
spec:
  replicas: 3
  selector:
    app: nodejs-app
  template:
    metadata:
      labels:
        app: nodejs-app
    spec:
      containers:
      - name: nodejs-app
        image: manhdaovan/nodejs-sample-app
        ports:
        - containerPort: 8080